import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:firebase_auth/firebase_auth.dart';

import '../bharosha/referrals.dart';
import '../bharosha/rules_loader.dart';

class EmergencyContactsScreen extends StatefulWidget {
  const EmergencyContactsScreen({Key? key}) : super(key: key);

  @override
  State<EmergencyContactsScreen> createState() =>
      _EmergencyContactsScreenState();
}

class _EmergencyContactsScreenState extends State<EmergencyContactsScreen> {
  // NOT WRITTEN HERE ANY MORE. Both lists are built from
  // assets/bharosha/referrals.json, generated by
  // bharosha_service/tools/export_shared.py from referrals.py.
  //
  // WHY. This screen kept its own copy of the numbers and their descriptions,
  // and the copies drifted: it described 16263 as "24/7 confidential support
  // for survivors of gender-based violence" while the chatbot — five taps away
  // in the same app, reading the shared list — correctly called it Shastho
  // Batayon, the national health line, and excluded it from every crisis
  // script for exactly that reason. The app contradicted itself about a
  // referral number, which is the one thing it cannot afford to do.
  //
  // Adding or relabelling a number is now a change to referrals.py and a
  // re-run of the exporter. A Python test fails while the generated files are
  // stale, so the two cannot drift again without the suite noticing.
  BharoshaRules? _rules;


  List<Helpline> get importantNumbers => _rules?.referrals.helplines ?? const [];

  List<FocalPoint> get safeguardingNumbers =>
      _rules?.referrals.focalPoints ?? const [];


  final List<bool> _expandedImportant = [];
  bool _expandedSafeguarding = false; // track safeguarding expand state

  @override
  void initState() {
    super.initState();
    BharoshaRules.load().then((rules) {
      if (!mounted) return;
      setState(() {
        _rules = rules;
        _expandedImportant
          ..clear()
          ..addAll(List.filled(importantNumbers.length, false));
      });
    });
  }

  void _launchDialer(String number) async {
    final url = Uri.parse('tel:$number');
    if (await canLaunchUrl(url)) {
      await launchUrl(url);
    }
  }

  void _launchEmail(String email) async {
    if (email.isEmpty) return;
    final url = Uri.parse('mailto:$email');
    if (await canLaunchUrl(url)) {
      await launchUrl(url);
    }
  }

  void _showLoginPopup() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text("Login required"),
        content: const Text(
            "You must be logged in to view the Safeguarding Focal(s) information."),
        actions: [
          TextButton(
            onPressed: () {
              Navigator.of(context).pop();
              Navigator.pushNamed(context, "/login"); // go to login page
            },
            child: const Text("Login"),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.deepPurple,
      appBar: AppBar(
        title: const Text(
          'Important Numbers',
          style: TextStyle(color: Colors.white),
        ),
        backgroundColor: Colors.deepPurple,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'National Helpline Numbers',
              style: TextStyle(
                  fontSize: 22,
                  fontWeight: FontWeight.bold,
                  color: Colors.white),
            ),
            const SizedBox(height: 12),
            ListView.separated(
              physics: const NeverScrollableScrollPhysics(),
              shrinkWrap: true,
              itemCount: importantNumbers.length,
              separatorBuilder: (_, __) => const SizedBox(height: 12),
              itemBuilder: (_, i) {
                final item = importantNumbers[i];
                return Card(
                  color: Colors.primaries[i % Colors.primaries.length][200],
                  child: Column(
                    children: [
                      ListTile(
                        contentPadding: const EdgeInsets.symmetric(
                            vertical: 12, horizontal: 16),
                        leading: IconButton(
                          icon: const Icon(Icons.phone,
                              size: 36, color: Colors.white),
                          onPressed: () => _launchDialer(item.number),
                        ),
                        title: Text(item.number,
                            style: const TextStyle(
                                fontWeight: FontWeight.bold, fontSize: 20)),
                        subtitle: Text(item.nameEn,
                            style: const TextStyle(fontSize: 16)),
                        trailing: IconButton(
                          icon: Icon(
                            _expandedImportant[i]
                                ? Icons.arrow_drop_up
                                : Icons.arrow_drop_down,
                            color: Colors.white,
                            size: 36,
                          ),
                          onPressed: () {
                            setState(() {
                              _expandedImportant[i] = !_expandedImportant[i];
                            });
                          },
                        ),
                      ),
                      if (_expandedImportant[i])
                        Padding(
                          padding: const EdgeInsets.only(
                              left: 16, right: 16, bottom: 12),
                          child: Text(item.descEn,
                              style: const TextStyle(fontSize: 14)),
                        ),
                    ],
                  ),
                );
              },
            ),
            const SizedBox(height: 24),

            // Safeguarding section
            ListTile(
              contentPadding: EdgeInsets.zero,
              title: const Text(
                'Safeguarding Focal(s)',
                style: TextStyle(
                    fontSize: 22,
                    fontWeight: FontWeight.bold,
                    color: Colors.white),
              ),
              trailing: IconButton(
                icon: Icon(
                  _expandedSafeguarding
                      ? Icons.arrow_drop_up
                      : Icons.arrow_drop_down,
                  size: 36,
                  color: Colors.white,
                ),
                onPressed: () {
                  final user = FirebaseAuth.instance.currentUser;
                  if (user == null) {
                    _showLoginPopup();
                  } else {
                    setState(() {
                      _expandedSafeguarding = !_expandedSafeguarding;
                    });
                  }
                },
              ),
            ),
            if (_expandedSafeguarding)
              Column(
                children: safeguardingNumbers.map((item) {
                  int index = safeguardingNumbers.indexOf(item);
                  return Card(
                    color: Colors.primaries[index % Colors.primaries.length]
                    [300],
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        ListTile(
                          contentPadding: const EdgeInsets.symmetric(
                              vertical: 12, horizontal: 16),
                          leading: IconButton(
                            icon: const Icon(Icons.phone,
                                size: 36, color: Colors.white),
                            onPressed: () =>
                                _launchDialer(item.number),
                          ),
                          title: Text(item.number,
                              style: const TextStyle(
                                  fontWeight: FontWeight.bold, fontSize: 20)),
                          subtitle: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(item.organisation,
                                  style: const TextStyle(
                                      fontWeight: FontWeight.w500)),
                              if (item.email.isNotEmpty)
                                Padding(
                                  padding: const EdgeInsets.only(top: 8.0),
                                  child: Row(
                                    crossAxisAlignment:
                                    CrossAxisAlignment.center,
                                    children: [
                                      IconButton(
                                        padding: EdgeInsets.zero,
                                        constraints: const BoxConstraints(),
                                        icon: const Icon(Icons.email,
                                            size: 24, color: Colors.white),
                                        onPressed: () => _launchEmail(item.email),
                                      ),
                                      const SizedBox(width: 8),
                                      Expanded(
                                        child: GestureDetector(
                                          onTap: () => _launchEmail(item.email),
                                          child: Text(
                                            item.email,
                                            style: const TextStyle(
                                                color: Colors.white,
                                                decoration:
                                                TextDecoration.underline),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  );
                }).toList(),
              ),
          ],
        ),
      ),
    );
  }
}
