"""Exports the safety rules, referral text and test cases for the Dart port.

    python tools/export_shared.py

THE DRIFT PROBLEM THIS SOLVES. The detection layer now runs twice: on the device
in Dart, so referrals appear instantly and offline, and on the server in Python,
as defence in depth for older app versions. Two hand-maintained copies of
life-safety patterns in two languages would diverge, and the divergence would be
invisible — a pattern fixed on the server, a phrase still missed on the phone.

So Python is the single author and Dart is a consumer. This script writes three
files, and tests/test_shared_export.py fails if they are stale, which makes
"regenerate after editing safety.py" a rule the suite enforces rather than a
habit someone has to remember.

    safety_rules.json   patterns, co-occurrence rules, categories, priority
    referrals.json      helplines, focal points, and every response, en + bn
    safety_cases.json   the shared test corpus both languages' tests run

Each is written twice: once into bharosha_service/shared/ for the container, and
once into the Flutter project's assets so the app can bundle them. The freshness
test compares the two copies byte for byte.

REGEX PORTABILITY. Dart's RegExp is JavaScript-flavoured and Python's re is not,
so the patterns deliberately stay inside the intersection: character classes,
alternation, \\b, \\s, {0,n}, non-capturing groups. No lookbehind, no named
groups, no possessive quantifiers, no \\p{...}. One real difference survives:
\\b is ASCII-only in Dart, which is why no Bangla pattern relies on it — Bangla
word boundaries are handled by the co-occurrence rules instead, which tokenise on
whitespace and behave identically in both languages.
"""

from __future__ import annotations

import json
import sys
from dataclasses import asdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "app"))

import referrals  # noqa: E402
import safety  # noqa: E402

SERVICE_SHARED = ROOT / "shared"
FLUTTER_ASSETS = (
    ROOT.parent / "stop_gender_violence_fresh_ui" / "assets" / "bharosha"
)

HEADER = (
    "GENERATED by bharosha_service/tools/export_shared.py — do not edit by hand. "
    "Edit app/safety.py or app/referrals.py and re-run the exporter; "
    "tests/test_shared_export.py fails while these files are stale."
)


def safety_rules() -> dict:
    return {
        "_generated": HEADER,
        "emergency_categories": list(safety.EMERGENCY_CATEGORIES),
        "refusal_categories": list(safety.REFUSAL_CATEGORIES),
        "greeting_categories": list(safety.GREETING_CATEGORIES),
        # Evaluation order matters: the first category that fires wins, so the
        # Dart port must walk this list in this order or the two will disagree on
        # messages that match more than one category.
        "priority": list(safety._PRIORITY),
        "invisible_characters": ["​", "‌", "‍", "﻿"],
        "patterns": {
            category: list(patterns)
            for category, patterns in safety._PATTERNS.items()
        },
        "near_rules": [
            {
                "category": rule.category,
                "first": list(rule.first),
                "second": list(rule.second),
                "window": rule.window,
                "note": rule.note,
            }
            for rule in safety._NEAR_RULES
        ],
    }


def referral_data() -> dict:
    return {
        "_generated": HEADER,
        "national_helplines": [asdict(line) for line in referrals.NATIONAL_HELPLINES],
        "safeguarding_focal_points": [
            asdict(point) for point in referrals.SAFEGUARDING_FOCAL_POINTS
        ],
        "safeguarding_email": referrals.SAFEGUARDING_EMAIL,
        "kaan_pete_roi": {
            "number": referrals.KAAN_PETE_ROI_NUMBER,
            "hours_en": referrals.KAAN_PETE_ROI_HOURS_EN,
            "hours_bn": referrals.KAAN_PETE_ROI_HOURS_BN,
        },
        "note_16263": referrals.NOTE_16263,
        # Rendered text, not templates: this is exactly what a frightened person
        # reads, and it is the thing to review. The numbers are interpolated
        # already; tests on both sides assert each response still carries them.
        "responses": referrals.RESPONSES,
        "answer_footer": {
            "en": referrals.ANSWER_FOOTER_EN,
            "bn": referrals.ANSWER_FOOTER_BN,
        },
    }


# The shared test corpus. Both pytest and `flutter test` run exactly these, which
# is what makes "ported with the same coverage" checkable instead of claimed.
CASES: list[dict] = [
    # --- emergencies, Bangla ---
    {"message": "আমাকে মারছে, বাঁচান", "kind": "emergency", "category": "immediate_danger"},
    {"message": "আমার স্বামী আমাকে মারধর করছে", "kind": "emergency", "category": "active_violence"},
    {"message": "সে আমাকে মেরে ফেলবে বলেছে", "kind": "emergency", "category": "threat_to_life"},
    {"message": "আমি আর বাঁচতে চাই না", "kind": "emergency", "category": "suicide_risk"},
    {"message": "আত্মহত্যা করতে ইচ্ছে করছে", "kind": "emergency", "category": "suicide_risk"},
    {"message": "আমি এখনই বিপদে আছি", "kind": "emergency", "category": "immediate_danger"},
    {"message": "আমি ভয় পাচ্ছি এখনই", "kind": "emergency", "category": "immediate_danger"},
    {"message": "আমার মেয়েকে যৌন নির্যাতন করা হয়েছে", "kind": "emergency", "category": "child_disclosure"},
    {"message": "নির্যাতন করা হয়েছে আমার মেয়েকে", "kind": "emergency", "category": "child_disclosure"},
    {"message": "আমার এলাকায় বাল্যবিবাহ হচ্ছে", "kind": "emergency", "category": "child_disclosure"},
    {"message": "একটি শিশুকে ধর্ষণ করা হয়েছে", "kind": "emergency", "category": "child_disclosure"},
    # --- emergencies, English ---
    {"message": "He is beating me right now", "kind": "emergency", "category": "active_violence"},
    {"message": "my husband just beat me", "kind": "emergency", "category": "active_violence"},
    {"message": "I am not safe, please help me now", "kind": "emergency", "category": "immediate_danger"},
    {"message": "I am scared right now", "kind": "emergency", "category": "immediate_danger"},
    {"message": "He said he will kill me", "kind": "emergency", "category": "threat_to_life"},
    {"message": "I want to die", "kind": "emergency", "category": "suicide_risk"},
    {"message": "I don't want to live anymore", "kind": "emergency", "category": "suicide_risk"},
    {"message": "My daughter was touched by her teacher", "kind": "emergency", "category": "child_disclosure"},
    {"message": "they abused my daughter", "kind": "emergency", "category": "child_disclosure"},
    {"message": "a child in our village is being abused", "kind": "emergency", "category": "child_disclosure"},
    {"message": "they want to marry off my daughter", "kind": "emergency", "category": "child_disclosure"},
    {"message": "she is only 14 and they want to marry her off", "kind": "emergency", "category": "child_disclosure"},
    # --- emergencies, romanised Bangla ---
    {"message": "amake marche help", "kind": "emergency", "category": "active_violence"},
    {"message": "se amake mere felbe", "kind": "emergency", "category": "threat_to_life"},
    {"message": "ami morte chai", "kind": "emergency", "category": "suicide_risk"},
    {"message": "ami bipode achi", "kind": "emergency", "category": "immediate_danger"},
    # --- refusals ---
    {"message": "Should I leave my husband?", "kind": "refuse", "category": "leave_decision"},
    {"message": "আমি কি স্বামীকে ছেড়ে চলে যাব", "kind": "refuse", "category": "leave_decision"},
    {"message": "How do I get a divorce in Bangladesh?", "kind": "refuse", "category": "divorce_process"},
    {"message": "বাংলাদেশে তালাক কীভাবে নেব?", "kind": "refuse", "category": "divorce_process"},
    {"message": "How do I collect evidence against him?", "kind": "refuse", "category": "confront_or_evidence"},
    {"message": "প্রমাণ জোগাড় করব কীভাবে", "kind": "refuse", "category": "confront_or_evidence"},
    {"message": "What are a woman's inheritance rights in Bangladesh?", "kind": "refuse", "category": "economic_rights"},
    {"message": "বাংলাদেশে নারীর উত্তরাধিকার অধিকার কী?", "kind": "refuse", "category": "economic_rights"},
    {"message": "Will I win the case?", "kind": "refuse", "category": "legal_advice"},
    {"message": "মামলা করলে কি জিতব", "kind": "refuse", "category": "legal_advice"},
    # --- precedence ---
    {"message": "He will kill me if I leave him", "kind": "emergency", "category": "threat_to_life"},
    {"message": "my daughter is being beaten by her father", "kind": "emergency", "category": "child_disclosure"},
    {"message": "he beats me and I want to die", "kind": "emergency", "category": "suicide_risk"},
    # --- ordinary questions, which must reach the corpus ---
    {"message": "What is safeguarding?", "kind": "proceed", "category": None},
    {"message": "সেফগার্ডিং মানে কী", "kind": "proceed", "category": None},
    {"message": "What is gender-based violence?", "kind": "proceed", "category": None},
    {"message": "জেন্ডারভিত্তিক সহিংসতা কী", "kind": "proceed", "category": None},
    {"message": "Who is responsible for safeguarding?", "kind": "proceed", "category": None},
    {"message": "How can violence be prevented in a community?", "kind": "proceed", "category": None},
    {"message": "What are the myths about GBV?", "kind": "proceed", "category": None},
    {"message": "ধন্যবাদ", "kind": "proceed", "category": None},
    # --- greetings, answered locally rather than over the network ---
    {"message": "hello", "kind": "greeting", "category": "greeting"},
    {"message": "hi", "kind": "greeting", "category": "greeting"},
    {"message": "Assalamu alaikum", "kind": "greeting", "category": "greeting"},
    {"message": "good morning", "kind": "greeting", "category": "greeting"},
    {"message": "নমস্কার", "kind": "greeting", "category": "greeting"},
    {"message": "আসসালামু আলাইকুম", "kind": "greeting", "category": "greeting"},
    {"message": "হ্যালো", "kind": "greeting", "category": "greeting"},
    # A greeting that carries a disclosure is NOT a greeting.
    {"message": "hi, he is beating me", "kind": "emergency", "category": "active_violence"},
    {"message": "hello, should I leave my husband?", "kind": "refuse", "category": "leave_decision"},
    # "hi" inside a real question must not be mistaken for one either.
    {"message": "What is safeguarding in this context?", "kind": "proceed", "category": None},
    # Window check: "daughter" and "abused" far apart must NOT fire the rule.
    {
        "message": (
            "my daughter asked about school and homework and dinner and bedtime "
            "and then we talked about the news where someone was abused"
        ),
        "kind": "proceed",
        "category": None,
    },
]


def test_cases() -> dict:
    enriched = []
    for case in CASES:
        decision = safety.classify(case["message"])
        if decision.kind != case["kind"] or decision.category != case["category"]:
            raise SystemExit(
                "Refusing to export: Python disagrees with a declared case.\n"
                f"  message : {case['message']}\n"
                f"  expected: {case['kind']}/{case['category']}\n"
                f"  actual  : {decision.kind}/{decision.category}"
            )
        enriched.append({**case, "language": decision.language})
    return {"_generated": HEADER, "cases": enriched}


def write(name: str, payload: dict) -> None:
    text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    for directory in (SERVICE_SHARED, FLUTTER_ASSETS):
        directory.mkdir(parents=True, exist_ok=True)
        (directory / name).write_text(text, encoding="utf-8")
    print(f"  {name}: {len(text):,} bytes -> shared/ and assets/bharosha/")


def main() -> int:
    print("Exporting shared rules, referrals and test cases")
    write("safety_rules.json", safety_rules())
    write("referrals.json", referral_data())
    write("safety_cases.json", test_cases())
    rules = safety_rules()
    print(
        f"\n  {len(rules['patterns'])} pattern groups, "
        f"{sum(len(v) for v in rules['patterns'].values())} patterns, "
        f"{len(rules['near_rules'])} co-occurrence rules, "
        f"{len(CASES)} shared test cases"
    )
    print(f"  Flutter assets: {FLUTTER_ASSETS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
